"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import Footer from "../components/Footer";


export default function TermsPage() {
  const [currentYear, setCurrentYear] = useState("2026");

  useEffect(() => {
    setCurrentYear(new Date().getFullYear().toString());
  }, []);

  return (
    <div className="flex-grow flex flex-col bg-white text-zinc-900">
      
      {/* Page Header */}
      <section className="py-12 sm:py-16 px-6 sm:px-8 border-b border-zinc-200 bg-white w-full text-center">
        <div className="max-w-4xl mx-auto flex flex-col items-center">
          <h1 className="text-2xl sm:text-4xl font-extrabold tracking-tight text-zinc-950 leading-tight mb-2">
            Terms and Conditions
          </h1>
          <p className="text-xs sm:text-sm text-zinc-500 max-w-md leading-relaxed">
            Last updated: May {currentYear}. Please review the terms of service governing the usage of PixelCode.

          </p>
        </div>
      </section>

      {/* Main Terms Body */}
      <section className="py-12 sm:py-16 px-6 sm:px-8 max-w-3xl mx-auto w-full flex-grow">
        <div className="flex flex-col gap-10 text-xs sm:text-sm leading-relaxed text-zinc-600">
          
          <div className="flex flex-col gap-3">
            <h2 className="text-sm font-bold text-zinc-900 tracking-tight">1. Usage License</h2>
            <p>
              By accessing and using PixelCode, you are granted a non-exclusive, non-transferable, revocable license to utilize the web application for generating screenshot images from code snippets. PixelCode operates entirely client-side, translating text blocks to localized browser representations. You may use generated images for any personal or commercial endeavors (including social media channels, blogs, technical documentation, and commercial portfolios) without attribution requirements.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <h2 className="text-sm font-bold text-zinc-900 tracking-tight">2. User Responsibilities</h2>
            <p>
              You agree not to utilize PixelCode to input or distribute content that is illegal, defamatory, threatening, abusive, harmful, or infringes upon the intellectual property rights of any individual or organization. You assume full legal responsibility for any code typed, pasted, or drag-and-dropped into the PixelCode application.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <h2 className="text-sm font-bold text-zinc-900 tracking-tight">3. Copyright & Intellectual Property</h2>
            <p>
              The code editor rendering interface, layouts, styles, brand name, and assets of PixelCode are the exclusive property of PixelCode. You retain full copyright ownership of the raw code snippets inputted and the styled screenshot images exported through the application. PixelCode makes no claims on intellectual property generated by its users.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <h2 className="text-sm font-bold text-zinc-900 tracking-tight">4. Generated Content</h2>
            <p>
              Because PixelCode executes processing on client devices, we do not store, review, moderate, or host any images or code snippets you insert. We assume no legal liability for public shares, code leaks, private api-token exposure, or screenshots posted to third-party social platforms. Please double-check your snippets for sensitive credentials prior to generating shareable assets.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <h2 className="text-sm font-bold text-zinc-900 tracking-tight">5. Limitation of Liability</h2>
            <p>
              PixelCode is provided "as is" and "as available" without any explicit or implied warranties. We do not guarantee that the application will function uninterrupted, error-free, or preserve styling configurations perfectly across all legacy web browsers. In no event shall PixelCode, its creators, or contributors be held liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use this styling platform.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <h2 className="text-sm font-bold text-zinc-900 tracking-tight">6. Updates to Terms</h2>
            <p>
              We reserve the right to revise or update these terms at our sole discretion. Any edits will take effect immediately upon being posted on this web page. Your continued use of the website following changes constitutes solid acceptance of the updated terms.
            </p>
          </div>

        </div>
      </section>

      {/* Global Footer */}
      <Footer />

    </div>
  );
}
